packages:
  - '.'
  - 'docs'
  - 'test-app'

ignoredBuiltDependencies:
  - esbuild

catalog:
  # Core framework
  next: ^16.0.10
  react: ^19.2.0
  react-dom: ^19.2.0

  # TypeScript
  typescript: ^5.9.3
  '@types/node': ^24.7.2
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2

  # Testing
  vitest: ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  jsdom: ^26.1.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.3.0

  # Linting & Formatting
  '@biomejs/biome': ^2.2.6
  prettier: ^3.5.3

  # CI/CD
  audit-ci: ^7.1.0
  semantic-release: ^25.0.2
