import './globals.css'

import { PublicEnvScript } from '@hyperb1iss/next-runtime-env'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <PublicEnvScript nonce={{ headerKey: 'x-nonce' }} />
            </head>
            <body className={inter.className}>{children}</body>
        </html>
    )
}
